# file generated by terraform. do not edit manually.
all:
  hosts:
  vars:
    ansible_user: ${ssh_username}
  children:
    servers:
      hosts:
        pavelzmon:
          ansible_host: ${dnsname}
